### PR TITLE
Added MathJax support

### PR DESCRIPTION
**Pull request by stuwhite**
Thanks for creating this plugin. I have just added a loader of the standard MathJax library so that equations in the asciidoc get rendered.

### CODE REVIEW

**Comment by christiangalsterer** [comment]
Thanks for providing the PR. I will review it over the weekend.

**Comment by christiangalsterer** [comment]
Looks ok to merge. 
I guess you did some testing?

**Comment by christiangalsterer** [comment]
@stuwhite: I did a little bit of testing and get only latexmath working but not asciimath. It is rendered correctly by asciidoctor.js, i.e. all quoting is added but this it where is stops. latexmath works like a charm. Did you experience the same? Maybe you can paste a snippet which worked for you?

**Comment by christiangalsterer** [comment]
Found the problem. I had to use a different MathJax configuration file.

**Comment by stuwhite** [comment]
Just read your comments: thanks for the update. I was using inline asciimath which was rendering: I have tested with the config you used and my test document is fine.

**Pull request merged**
